spring:
  application:
    name: Api-gw
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: usuarios
        format_sql: true
        ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  # Spring Cloud Gateway Configuration
  config:
    import: optional:file:${GATEWAY_ROUTES}
server:
  port: 8200
  ssl:
    enabled: true
    key-store: ${SSL_FILE}
    key-store-password: ${SSL_PASS}
    key-store-type: PKCS12
    key-alias: api-gw
jwt:
  secret: ${JWT_SECRET}
logging:
  pattern:
    dateformat: HH:mm
springdoc:
  swagger-ui:
    path: /docs
