spring:
  application:
    name: Tienda_back
  datasource:
    url: jdbc:mysql://192.168.1.77:4000/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  # Spring Cloud Gateway Configuration
  cloud:
    gateway:
      mvc:
        routes:
          - id: jokes
            uri: https://api.chucknorris.io/jokes/random
            predicates:
              - Path=/jokes, /jokes/**
            filters:
              - RewritePath=/jokes/(?<segment>.*), /jokes/${segment}
          - id: pedidos
            uri: http://192.168.1.77:9000
            predicates:
              - Path=/pedido/**, /cupon/**
            filters:
              - RewritePath=/(?<first>pedido|cupon)/(?<segment>.*), /${first}/${segment}
          - id: productos_categorias
            uri: http://192.168.1.77:3000
            predicates:
              - Path=/productos/**
            filters:
              - RewritePath=/productos/(?<segment>.*), /api/${segment}
server:
  port: 8200

jwt:
  secret: OWlRMWhGajJ0cXUvMUJ4WGtnbDlackUyT1p5UmxRSXZSTXFHdHFOdURsdz0=

logging:
  pattern:
    dateformat: HH:mm

springdoc:
  swagger-ui:
    path: /docs
